ownreader/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from ownreader.forms import AddFeedForm, AddFeedFormPreview

urlpatterns = patterns(
    '',
    url(r'^$', 'ownreader.views.index', name='index'),
    url(r'^addfeed/$', login_required(AddFeedFormPreview(AddFeedForm)),
        name='addFeed'),
	url(r'^settings/$', 'ownreader.views.settings', name='settings'),
    url(r'^update$', 'ownreader.views.update', name='UserUpdate'),
    url(r'^toggleRead$', 'ownreader.views.toggleRead', name="toggleRead"),
    url(r'^toggleShowRead$', 'ownreader.views.toggleShowRead', name="toggleShowRead"),
    url(r'^toggleSidebar$', 'ownreader.views.toggleSidebar', name="toggleSidebar"),
    url(r'^markRead$', 'ownreader.views.markRead', name="markRead"),
)

woereader/urls.py
from django.conf.urls import patterns, include, url
from woereader.forms import FormWithCaptcha
from django.views.generic import TemplateView
from registration.backends.default.views import RegistrationView
from django.contrib.auth import views as auth_views
from django.contrib import admin
admin.autodiscover()

class RecaptchaRegistrationView(RegistrationView):
    form_class = FormWithCaptcha

urlpatterns = patterns(
    '',
    url(r'', include('ownreader.urls', namespace="ownreader")),
    url(r'^accounts/register/$', RecaptchaRegistrationView.as_view(),
        name='registration_register'),
    #override the default urls for django-registration's sake
    url(r'^password/change/$', auth_views.password_change,
        name='password_change'),
    url(r'^password/change/done/$', auth_views.password_change_done,
        name='password_change_done'),
    url(r'^password/reset/$', auth_views.password_reset,
        name='password_reset'),
    url(r'^password/reset/done/$', auth_views.password_reset_done,
        name='password_reset_done'),
    url(r'^password/reset/complete/$', auth_views.password_reset_complete,
        name='password_reset_complete'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        name='password_reset_confirm'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^accounts/profile/$', 'ownreader.views.index', name='index'),
    url(r'^admin/', include(admin.site.urls)),
)

ownreader/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now


class Feed(models.Model):
    title = models.CharField(max_length=1000)
    description = models.CharField(max_length=1000)
    url = models.URLField(unique=True)
    updated = models.DateTimeField(default=now())
    checked = models.DateTimeField(default=now())
    etag = models.CharField(blank=True, max_length=500)
    users = models.ManyToManyField(User, through='UserFeed')


class UserFeed(models.Model):
    user = models.ForeignKey(User)
    feed = models.ForeignKey(Feed)
    customTitle = models.CharField(max_length=500)
    customDescription = models.CharField(max_length=1000)


class Item(models.Model):
    feed = models.ForeignKey(Feed)
    title = models.CharField(max_length=1000)
    itemId = models.CharField(max_length=255, unique=True)
    url = models.URLField()
    published = models.DateTimeField(default=now())
    description = models.TextField()
    content = models.TextField()
    users = models.ManyToManyField(User, through='UserItem')


class UserItem(models.Model):
    bookmarked = models.BooleanField(default=False)
    read = models.BooleanField(default=False)
    user = models.ForeignKey(User)
    item = models.ForeignKey(Item)


class Folder(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    user = models.ForeignKey(User)
    feeds = models.ManyToManyField(UserFeed)


class UserPrefs(models.Model):
    user = models.ForeignKey(User)
    showRead = models.BooleanField(default=False)
    showSidebar = models.BooleanField(default=True)
    AUTOEXPAND = 'AX'
    COLLAPSED = 'CO'
    EXPANDED = 'EX'
    TALL = 'TA'
    WIDE = 'WI'
    VIEWMODE_CHOICES = ((AUTOEXPAND, 'Auto-Expand'),
                        (COLLAPSED, 'Collapsed'),
                        (EXPANDED, 'Expanded'),
                        (TALL, 'Tall'),
                        (WIDE, 'Wide'),)
    viewMode = models.CharField(max_length=2,
                                choices=VIEWMODE_CHOICES,
                                default=EXPANDED)
    ITEMNUMBER_CHOICES = map(
        lambda x:(x,x),[10,20,25,30,40,50,60,70,75,80,90,100])
    itemsPerPage = models.IntegerField(choices=ITEMNUMBER_CHOICES, default=25)

ownreader/forms.py
from django import forms
from django.contrib.formtools.preview import FormPreview
from django.forms.models import modelformset_factory
from ownreader.feeds import ParseFeed, AddFeed
from ownreader.models import UserItem, UserPrefs
from django.shortcuts import redirect


class AddFeedForm(forms.Form):
    feed = forms.URLField(label="Feed URL:")

    def clean_feed(self):
        feed = self.cleaned_data['feed']
        validate = ParseFeed(feed)
        if validate['invalid']:
            reason = ''.join(validate['invalid'])
            raise forms.ValidationError("No valid feed at URL provided " +
                                        " (" + reason + ")")
        return feed


class AddFeedFormPreview(FormPreview):
    preview_template = 'ownreader/feed.html'
    form_template = 'ownreader/feed_form.html'

    def process_preview(self, request, form, context):
        context['parsed'] = ParseFeed(form.cleaned_data['feed'])

    def done(self, request, cleaned_data):
        AddFeed(cleaned_data['feed'], request.user)
        return redirect('/')


MarkAllReadFormSet = modelformset_factory(
                                          UserItem,
                                          fields=('id','read',),
                                          extra=0,
                                          widgets={'read': forms.HiddenInput})

class UserPrefsForm(forms.ModelForm):
    class Meta(object):
        fields = ('viewMode', 'itemsPerPage')

ownreader/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.decorators.csrf import ensure_csrf_cookie
from django.http import HttpResponse
from ownreader.models import UserItem, UserPrefs
from ownreader.tasks import CeleryUpdater
from ownreader.forms import MarkAllReadFormSet, UserPrefsForm
from django.core.paginator import Paginator, EmptyPage


@ensure_csrf_cookie
def index(request):
    if not request.user.is_authenticated():
        return render(request, 'ownreader/welcome.html')

    showRead = request.POST.get('showRead', None)
    pageSize = request.POST.get('pageSize', None)
    newestItem = request.POST.get('newest', None)
    adding = request.POST.get('adding', False)
    page = request.POST.get('page', 1)
    selected = request.POST.get('selected', None)

    if page != 1:
        page = int(page)

    #Grab the current user's preferences for the layout
    prefs = None
    try:
        prefs = UserPrefs.objects.get(user=request.user)
    except:
        pass
    if prefs is None:
        prefs = UserPrefs(user=request.user)
        prefs.save()

    #Apply the user preferences if we didn't get POST specifics
    if showRead is None:
        showRead = prefs.showRead
    elif showRead == "True":
        showRead = True
    else:
        showRead = False

    if pageSize is not None:
        try:
            pageSize = int(pageSize)
        except:
            pass

    if pageSize is None:
        pageSize = prefs.itemsPerPage


    #Grab the items to show, depending on read status preference
    items = UserItem.objects.select_related('item').filter(
                user=request.user
            ).order_by(
                '-item__published')

    if not showRead:
        items = items.filter(read=False)

    #Ensure updates don't alter items' places in the page
    if newestItem is not None:
        try:
            newestItem = int(newestItem)
            latestUserItem = UserItem.objects.get(pk=newestItem)
            latestItem = latestUserItem.item
            items = items.filter(item__published__lte=latestItem.published)
        except:
            pass


    #Paginate the items, check if a particular page was requested
    paginator = Paginator(items, pageSize)
    currentItems = None;
    try:
        currentItems = paginator.page(page)
    except EmptyPage:
        currentItems = paginator.page(paginator.num_pages)
    except:
        pass
    if currentItems is None:
        currentItems = paginator.page(1)

    if adding is False:
        formsetItems = items.filter(id__in=[item.id for item in currentItems])
    else:
        allPages = Paginator(items, pageSize*page)
        currItems = allPages.page(1)
        formsetItems = items.filter(id__in=[item.id for item in currItems])

    #Chose which item to display in the preview
    if selected is not None:
        try:
            selected = currentItems[int(selected)]
        except:
            selected = None
    if selected is None and len(currentItems) > 0:
        selected = currentItems[0]

    allItems = MarkAllReadFormSet(queryset=formsetItems)

    context = {'items': currentItems,
               'formset': allItems,
               'prefs': prefs,
               'selected': selected}
    return render(request, 'ownreader/index.html', context)


def update(request):
    if request.user.is_authenticated():
        CeleryUpdater.delay(request.user)
    return redirect('/')


#Marks an item with the read status requested if one is given, else toggles
def toggleRead(request):
    if request.user.is_authenticated():
        if request.method == "POST":
            item = None
            read = None
            try:
                item = UserItem.objects.get(pk=request.POST['id'])
            except:
                pass
            try:
                read = request.POST['read']
            except:
                pass
            if item is not None and item.user == request.user:
                if read is not None:
                    if read == "True":
                        item.read = True
                    elif read == "False":
                        item.read = False
                else:
                    if item.read:
                        item.read = False
                    else:
                        item.read = True
                item.save()
    return redirect('/')


def markRead(request):
    if request.user.is_authenticated():
        if request.method == "POST":
            allItems = MarkAllReadFormSet(request.POST)
            instances = allItems.save(commit=False)
            for instance in instances:
                instance.read = True
                instance.save()
    return redirect('/')


def toggleShowRead(request):
    if request.user.is_authenticated():
        prefs = UserPrefs.objects.get(user=request.user)
        if prefs.showRead:
            prefs.showRead = False
        else:
            prefs.showRead = True
        prefs.save()
    return redirect('/')


def toggleSidebar(request):
    if request.user.is_authenticated():
        try:
            prefs = UserPrefs.objects.get(user=request.user)
        except:
            pass
        if request.method == "POST":
            if request.POST.get('showSidebar') == 'toggle':
                prefs.showSidebar = bool(not prefs.showSidebar)
                prefs.save()
            return HttpResponse(201)
        else:
            prefs.showSidebar = bool(not prefs.showSidebar)
            prefs.save()
    return redirect('/')


@login_required
def settings(request):
    prefs = UserPrefs.objects.filter(user=request.user).first()
    form = UserPrefsForm(request.POST or None, instance=prefs)

    if request.method == 'POST':
        if form.is_valid():
            form.save();
            return redirect('/')

    return render(request, 'ownreader/forms.html', {
        'form': form,
    })

templates/ownreader/dialog.html
{% extends "base.html" %}
{% block content %}
    <div id="aligned_div">
        {% block textcontent %}
        {% endblock %}
        {% block extracontent %}
        {% endblock extracontent %}
    </div>
{% endblock content %}

templates/ownreader/feed.html
{% extends "ownreader/forms.html" %}
{% block formcontent %}
    <p><label></label><input type="submit" value="Add/Preview" /></p><br />
    <input type="hidden" name="{{ stage_field }}" value="2" />
    <input type="hidden" name="{{ hash_field }}" value="{{ hash_value }}" />
{% endblock %}

{% block extracontent %}
    <div id="itemWrapper">
        <h1 class="centredText">
            <a href="{{ feed }}">
                {{ parsed.title }}
                {% if parsed.description %}
                    ({{ parsed.description }})
                    {% endif %}
                {% if parsed.invalid %}
                {{ parsed.invalid }}
                {% endif %}
            </a>
        </h1><br />
        {% for key, item in parsed.entries.items %}
        <div class="item">
            <div class="item_header">
                <div class="item_title">
                    <h3>
                        <a href="{{ item.link }}">{{ item.title }} ({{ item.updated }})</a>
                    </h3>
                </div>
            </div>
            <div class="item_summary">
                {{ item.content|safe }}
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock extracontent %}

templates/ownreader/feed_form.html
{% extends "ownreader/forms.html" %}
{% block formcontent %}
<p>
    <label for="submit"></label>
    <input type="submit" value="Preview">
</p>
{% endblock %}

templates/ownreader/forms.html
{% extends "ownreader/dialog.html" %}
{% block textcontent %}
    <form method="post" action=".">
        {% csrf_token %}
            {% if form.errors %}
                {{ form.errors|pluralize }}
            {% endif %}
            {% for field in form  %}
                {{ field.error }}
                {{ field.field.error }}
            {% endfor %}
            {{ form.non_field_errors }}
            {{ form.as_p }}
        {% block formcontent %}
            <p>
                <label for="submit"></label>
                <input type="submit" value="Save">
            </p>
        {% endblock formcontent%}
    </form>
{% endblock textcontent %}

templates/ownreader/index.html
{% extends "base.html" %}
{% block scripts %}
	<script src="{{ STATIC_URL }}js/jquery.mobile.js"></script>
	<script src="{{ STATIC_URL }}js/jquery.util-functions.js"></script>
	<script src="{{ STATIC_URL }}js/jquery.infinite-scroll.js"></script>
	<script src="{{ STATIC_URL }}js/feed.js"></script>
{% endblock scripts %}

{% block appmenu %}
	<li class="menu">
		<a class="symbol" href="{% url 'ownreader:addFeed' %}">&#8862;</a>
	</li>
	<li class="menu">
		<a class="symbol" href="{% url 'ownreader:UserUpdate' %}">&#128260;</a>
	</li>
	<li class="menu">
		<a class="symbol" href="{% url 'ownreader:toggleSidebar' %}"
		    id="sidebarToggle" onclick="WOE.toggleSidebar(); return false;">
		    &#128193;
		</a>
	</li>
	<li class="menu">
		<form action="{% url 'ownreader:markRead' %}" method="post"
		    id="allItemsForm">
            {% csrf_token %}
		    {{ formset }}
		    <button class="symbol" onclick="WOE.markAllAsRead(); return false;">
		        &#59146;
		    </button>
		</form>
{% endblock %}

{% block usermenu %}
    {% if prefs.showRead %}
	    <li><a href="{% url 'ownreader:toggleShowRead' %}">Hide Read</a></li>
	{% else %}
	    <li><a href="{% url 'ownreader:toggleShowRead' %}">View Read</a></li>
	{% endif %}
{% endblock %}

{% block wrapperclasses %}
    class="
    {% if prefs.showSidebar %}sidebar{% endif %}
    {% if prefs.viewMode == "CO" %}collapse
        {% elif prefs.viewMode == "AX" %}autoexpand
        {% elif prefs.viewMode == "EX" %}expand
        {% elif prefs.viewMode == "TA" %}tall
        {% elif prefs.viewMode == "WI" %}wide
    {% endif %}
    "
{% endblock %}

{% block content %}
<div id="asidewrapper">
	<aside>
		<p>
			-----sidebar-----
		</p>
	</aside>
</div>
<div id="mainWrapper">
    <div id="itemWrapper">
    {% if items.has_previous %}
        <form action="/" method="post" id="previousPage" class="non-js">
            {% csrf_token %}
            <input name="page" type="hidden"
                value="{{ items.previous_page_number }}" />
            <input class="widebutton" type="submit" value="Newer Entries">
        </form>
    {% endif %}
    {% for item in items %}
        <div class="item
            {% if item.read %}read{% endif %}
            {% if prefs.viewMode != "EX" %}collapsed{% endif %}"
            id="{{ item.pk }}">
            <div class="item_header">
                <div class="item_title" onclick="WOE.selectItem({{ item.pk }})">
                    <h3>
                        <a href="{{ item.item.url }}">{{ item.item.title }}</a>
                    </h3>
                </div>
                <div class="item_actions">
                    <button onclick="WOE.toggleShow({{ item.pk }})" class="hider">
                        {% if prefs.viewMode == "EX" %}-
                        {% else %}+
                        {% endif %}
                    </button>
                    <form action={% url 'ownreader:toggleRead' %} method="post">
                        {% csrf_token %}
                        <input name="id" type="hidden" value="{{ item.pk }}" />
                        <input type="submit" value="Read"
                            onclick="WOE.toggleRead({{ item.pk }}); return false;">
                    </form>
                </div>
            </div>
            <div class="item_summary">
                {{item.item.content|safe}}
            </div>
        </div>
    {% endfor %}
    {% if items.has_next %}
        <form action="/" method="post" id="nextPage" class="non-js">
            {% csrf_token %}
            <input name="items" id="itemsPerPage" type="hidden"
                value="{{ prefs.itemsPerPage }}" />
            <input name="showRead" id="showRead" type="hidden"
                value="{{ prefs.showRead }}" />
            <input name="page" id="newPage" type="hidden"
                value="{{ items.next_page_number }}" />
            <input class="widebutton" type="submit" value="Older Entries">
        </form>
    {% endif %}
    </div>
    <div id="previewWrapper">
        <div id="preview"></div>
        <div id="preview_actions">
            <ul class="leftfloat">
                <li class="menu smallscreen">
                    <a class="symbol" href="#"
                        onclick="WOE.hidePreview(); return false;">&#58541;</a>
                </li>
                <li class="menu">
                    <form action={% url 'ownreader:toggleRead' %} method="post">
                        {% csrf_token %}
                        <input name="id" type="hidden" value="" />
                        <button class="symbol" id="previewMarkRead"
                            onclick="WOE.toggleRead({{ selected.id }}); return false;">
                            &#59146;
                        </button>
                    </form>
                </li>
            </ul>
            <ul class="rightfloat">
                <li class="menu">
                    <a class="symbol" href="#" id="viewPreviousItem"
                        onclick="WOE.previousItem(); return false;">
                        &#59233;
                    </a>
                </li>
                <li class="menu">
                    <a class="symbol" href="#" id="viewNextItem"
                        onclick="WOE.nextItem(); return false;">
                        &#59234;
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

templates/ownreader/welcome.html
{% extends "ownreader/dialog.html" %}
{% block textcontent %}
<p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc gravida purus
    in nibh iaculis rutrum. Mauris ullamcorper sagittis libero, a rhoncus magna
    aliquam in. Suspendisse sapien sapien, condimentum eget sodales non,
    commodo vel est. Aenean feugiat mollis facilisis. Vivamus interdum lorem
    quis felis rhoncus porttitor. Sed ullamcorper rutrum molestie. Integer quis
    dui vitae odio egestas imperdiet. Nunc in massa eget felis lacinia eleifend
    non quis diam. Suspendisse quis scelerisque metus.

    Aliquam luctus, odio eu consequat congue, tortor felis aliquet arcu, quis
    rhoncus lacus eros et lorem. Maecenas nec pulvinar justo. Proin odio orci,
    tincidunt a semper sit amet, egestas nec neque. Ut lorem elit, egestas a
    cursus luctus, porttitor in magna. Praesent ut felis a neque posuere tempus
    vitae quis orci. Praesent porttitor lacus ac justo porttitor ac porttitor
    urna semper. In sollicitudin risus non ante blandit auctor.

    Mauris et malesuada orci. Nulla hendrerit faucibus nulla, ut bibendum dui
    molestie id. Sed facilisis auctor nunc, ac accumsan justo bibendum quis.
    Fusce et augue dolor, vel euismod arcu. Donec aliquam consectetur
    malesuada. Mauris at suscipit est. Cum sociis natoque penatibus et magnis
    dis parturient montes, nascetur ridiculus mus. Maecenas condimentum euismod
    ante ut aliquam.

    Pellentesque tortor sapien, eleifend ac sagittis quis, posuere et lacus.
    Aenean quis sapien mi. Duis mollis tempus nisl in porta. Etiam volutpat
    ipsum a justo luctus scelerisque. Sed felis dolor, vestibulum in tempor ac,
    sodales non dui. Pellentesque habitant morbi tristique senectus et netus et
    malesuada fames ac turpis egestas. Aliquam vitae imperdiet dui. Class
    aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos
    himenaeos. Fusce nisl justo, lacinia nec lacinia vel, molestie quis libero.
    Aenean a felis est. Vestibulum eget metus nec diam condimentum porttitor.

    Nunc rhoncus consequat nisi, quis pretium odio pellentesque a. Fusce
    rhoncus dui in turpis posuere mattis. Ut eros sapien, iaculis in lacinia
    fermentum, iaculis laoreet felis. Donec viverra, nisl non consectetur
    tincidunt, elit metus elementum urna, sit amet suscipit ligula nisl ac
    purus. Praesent eu lectus vel diam porta semper. Pellentesque eget
    dignissim massa. Fusce magna nulla, convallis nec sagittis ac, auctor non
    dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices
    posuere cubilia Curae; Donec mollis metus a sem tincidunt sagittis. Morbi
    et dui at enim ornare fringilla. Class aptent taciti sociosqu ad litora
    torquent per conubia nostra, per inceptos himenaeos. Donec congue varius
    laoreet. Mauris ultrices felis ac felis cursus sit amet lacinia nulla
    consequat. Ut neque ipsum, laoreet et consequat eget, consectetur id orci.
    Suspendisse ut sem malesuada massa placerat ultrices. Pellentesque habitant
    morbi tristique senectus et netus et malesuada fames ac turpis egestas. 
</p>
{% endblock %}