ownreader/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from ownreader.forms import AddFeedForm, AddFeedFormPreview

urlpatterns = patterns(
    '',
    url(r'^$', 'ownreader.views.index', name='index'),
    url(r'^addfeed/$', login_required(AddFeedFormPreview(AddFeedForm)),
        name='addFeed'),
	url(r'^settings/$', 'ownreader.views.settings', name='settings'),
    url(r'^update$', 'ownreader.views.update', name='UserUpdate'),
    url(r'^toggleRead$', 'ownreader.views.toggleRead', name="toggleRead"),
    url(r'^toggleShowRead$', 'ownreader.views.toggleShowRead', name="toggleShowRead"),
    url(r'^toggleSidebar$', 'ownreader.views.toggleSidebar', name="toggleSidebar"),
    url(r'^markRead$', 'ownreader.views.markRead', name="markRead"),
)

woereader/urls.py
from django.conf.urls import patterns, include, url
from woereader.forms import FormWithCaptcha
from django.views.generic import TemplateView
from registration.backends.default.views import RegistrationView
from django.contrib.auth import views as auth_views
from django.contrib import admin
admin.autodiscover()

class RecaptchaRegistrationView(RegistrationView):
    form_class = FormWithCaptcha

urlpatterns = patterns(
    '',
    url(r'', include('ownreader.urls', namespace="ownreader")),
    url(r'^accounts/register/$', RecaptchaRegistrationView.as_view(),
        name='registration_register'),
    #override the default urls for django-registration's sake
    url(r'^password/change/$', auth_views.password_change,
        name='password_change'),
    url(r'^password/change/done/$', auth_views.password_change_done,
        name='password_change_done'),
    url(r'^password/reset/$', auth_views.password_reset,
        name='password_reset'),
    url(r'^password/reset/done/$', auth_views.password_reset_done,
        name='password_reset_done'),
    url(r'^password/reset/complete/$', auth_views.password_reset_complete,
        name='password_reset_complete'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        name='password_reset_confirm'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^accounts/profile/$', 'ownreader.views.index', name='index'),
    url(r'^admin/', include(admin.site.urls)),
)

templates/base.html
{% load url from future %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta name="viewport" content="width=device-width, user-scalable=no">
		<link rel="stylesheet" href="{{ STATIC_URL }}css/normalize.css" />
		<link rel="stylesheet" href="{{ STATIC_URL }}css/main.css" />
		<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
		<script src="{{ STATIC_URL }}js/jquery.dropdown-menu.js"></script>
		{% block scripts %}{% endblock scripts %}
		<title>{% block title %}Woereader{% endblock %}</title>
	<meta charset="utf-8" />
</head>

<body>
	<div id="smallscreen"></div>
	<nav>
		{% block navbar %}
		<ul class="leftfloat">
			<li class="menu">
				<a class="symbol" href="{% url 'ownreader:index' %}">&#8962;</a>
			</li>
			{% if user.is_authenticated %}
			    {% block appmenu %}
			    {% endblock appmenu %}
			{% endif %}
		</ul>
		<ul class="rightfloat">
			<li class="menu"><a class="symbol" href="#">&#9881;</a>
				<ul>
					{% if user.is_authenticated %}
						{% block usermenu %}
						{% endblock %}
                        <li><a href="{% url 'ownreader:settings' %}">Settings</a></li>
						<li><a href="{% url 'auth_logout' %}">Log Out</a></li>
					{% else %}
						<li><a href="{% url 'auth_login' %}">Log In</a></li>
					{% endif %}
				</ul>
			</li>
		</ul>
		{% endblock navbar %}
	</nav>
	<div id="wrapper"{% block wrapperclasses %}{% endblock %}>
		{% block content %}
		{% endblock %}
	</div>
</body>
</html>